# Generated by Django 2.2.28 on 2023-06-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20230609_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountOfIngredient',
        ),
    ]
