# Generated by Django 2.2.28 on 2023-06-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230609_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCart',
        ),
    ]
